language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=cov
    - TOXENV=sith
matrix:
    allow_failures:
        - env: TOXENV=cov
        - env: TOXENV=sith
        - env: TOXENV=pypy
install:
    - pip install --quiet --use-mirrors tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi
